// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: checkIfEmailIsInUse.sql

package db

import (
	"context"
)

const checkIfEmailIsInUse = `-- name: CheckIfEmailIsInUse :one
select exists(select id, name, email, email_verified, picture, account_password, created_at, last_login, refresh_token, deleted, signup_mode from userr where email = $1)
`

func (q *Queries) CheckIfEmailIsInUse(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfEmailIsInUse, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
