// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: contactSupport.sql

package db

import (
	"context"
)

const contactSupport = `-- name: ContactSupport :one
insert into support (id, email, title, comment)
values ($1, $2, $3, $4)
returning id, email, title, comment, created
`

type ContactSupportParams struct {
	ID      string `json:"id"`
	Email   string `json:"email"`
	Title   string `json:"title"`
	Comment string `json:"comment"`
}

func (q *Queries) ContactSupport(ctx context.Context, arg ContactSupportParams) (Support, error) {
	row := q.db.QueryRow(ctx, contactSupport,
		arg.ID,
		arg.Email,
		arg.Title,
		arg.Comment,
	)
	var i Support
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Title,
		&i.Comment,
		&i.Created,
	)
	return i, err
}
