// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: createBookmarkScreenshot.sql

package db

import (
	"context"
)

const createBookmarkScreenshot = `-- name: CreateBookmarkScreenshot :one
insert into bookmark_screenshots(id, screenshot_location, bookmark_id, user_id, fullpage)
values ($1, $2, $3, $4, $5)
returning id, screenshot_location, bookmark_id, user_id, added, deleted, fullpage
`

type CreateBookmarkScreenshotParams struct {
	ID                 string `json:"id"`
	ScreenshotLocation string `json:"screenshot_location"`
	BookmarkID         string `json:"bookmark_id"`
	UserID             string `json:"user_id"`
	Fullpage           bool   `json:"fullpage"`
}

func (q *Queries) CreateBookmarkScreenshot(ctx context.Context, arg CreateBookmarkScreenshotParams) (BookmarkScreenshot, error) {
	row := q.db.QueryRow(ctx, createBookmarkScreenshot,
		arg.ID,
		arg.ScreenshotLocation,
		arg.BookmarkID,
		arg.UserID,
		arg.Fullpage,
	)
	var i BookmarkScreenshot
	err := row.Scan(
		&i.ID,
		&i.ScreenshotLocation,
		&i.BookmarkID,
		&i.UserID,
		&i.Added,
		&i.Deleted,
		&i.Fullpage,
	)
	return i, err
}
