// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: createPocketCode.sql

package db

import (
	"context"
)

const createPocketCode = `-- name: CreatePocketCode :one
insert into pocket_code (user_id, code)
values ($1, $2)
on conflict(user_id) do update set code = excluded.code
returning user_id, code
`

type CreatePocketCodeParams struct {
	UserID string `json:"user_id"`
	Code   string `json:"code"`
}

func (q *Queries) CreatePocketCode(ctx context.Context, arg CreatePocketCodeParams) (PocketCode, error) {
	row := q.db.QueryRow(ctx, createPocketCode, arg.UserID, arg.Code)
	var i PocketCode
	err := row.Scan(&i.UserID, &i.Code)
	return i, err
}
