// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: createBookmarkTag.sql

package db

import (
	"context"
)

const bookmarkTag = `-- name: BookmarkTag :one
INSERT INTO bookmark_tag (bookmark_id, tag_id)
VALUES ($1, $2)
RETURNING bookmark_id, tag_id
`

type BookmarkTagParams struct {
	BookmarkID string `json:"bookmark_id"`
	TagID      string `json:"tag_id"`
}

func (q *Queries) BookmarkTag(ctx context.Context, arg BookmarkTagParams) (BookmarkTag, error) {
	row := q.db.QueryRow(ctx, bookmarkTag, arg.BookmarkID, arg.TagID)
	var i BookmarkTag
	err := row.Scan(&i.BookmarkID, &i.TagID)
	return i, err
}
