// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: deleteEmailVerificationToken.sql

package db

import (
	"context"
)

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
delete from email_verification where email = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, email)
	return err
}
