// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: getBookmarkByIdAndUserId.sql

package db

import (
	"context"
)

const getBookmarkByIdAndUserId = `-- name: GetBookmarkByIdAndUserId :one
select id, title, bookmark, host, favicon, thumbnail, notes, user_id, added, updated, deleted from bookmark where id =$1 and user_id = $2 limit 1
`

type GetBookmarkByIdAndUserIdParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetBookmarkByIdAndUserId(ctx context.Context, arg GetBookmarkByIdAndUserIdParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, getBookmarkByIdAndUserId, arg.ID, arg.UserID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Bookmark,
		&i.Host,
		&i.Favicon,
		&i.Thumbnail,
		&i.Notes,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}
