// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: getBookmarkByID.sql

package db

import (
	"context"
)

const getBookmarkByID = `-- name: GetBookmarkByID :one
select id, title, bookmark, host, favicon, thumbnail, notes, user_id, added, updated, deleted, folder_id, beautified from bookmark where id = $1 and deleted is null limit 1
`

func (q *Queries) GetBookmarkByID(ctx context.Context, id string) (Bookmark, error) {
	row := q.db.QueryRow(ctx, getBookmarkByID, id)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Bookmark,
		&i.Host,
		&i.Favicon,
		&i.Thumbnail,
		&i.Notes,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
		&i.FolderID,
		&i.Beautified,
	)
	return i, err
}
