// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: getBookmarkTags.sql

package db

import (
	"context"
)

const getBookmarkTags = `-- name: GetBookmarkTags :many
select tag_id from bookmark_tag where bookmark_id = $1
`

func (q *Queries) GetBookmarkTags(ctx context.Context, bookmarkID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getBookmarkTags, bookmarkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
