// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: getBookmarksInTrash.sql

package db

import (
	"context"
)

const getBookmarksInTrash = `-- name: GetBookmarksInTrash :many
select id, title, bookmark, host, favicon, thumbnail, notes, user_id, added, updated, deleted, folder_id, beautified from bookmark where deleted is not null and user_id = $1 order by deleted desc
`

func (q *Queries) GetBookmarksInTrash(ctx context.Context, userID string) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, getBookmarksInTrash, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Bookmark,
			&i.Host,
			&i.Favicon,
			&i.Thumbnail,
			&i.Notes,
			&i.UserID,
			&i.Added,
			&i.Updated,
			&i.Deleted,
			&i.FolderID,
			&i.Beautified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
