// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: getFolderPath.sql

package db

import (
	"context"
)

const getFolderPath = `-- name: GetFolderPath :many
select folder_id, user_id, folder_name, path, label, starred, created_at, updated_at, subfolder_of, deleted_at, folder_description, folder_password, ishidden from folder where folder.path @> (select path from folder as f where f.label = $1) order by path
`

func (q *Queries) GetFolderPath(ctx context.Context, label string) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFolderPath, label)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.FolderID,
			&i.UserID,
			&i.FolderName,
			&i.Path,
			&i.Label,
			&i.Starred,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubfolderOf,
			&i.DeletedAt,
			&i.FolderDescription,
			&i.FolderPassword,
			&i.Ishidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
