// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: getPocketCode.sql

package db

import (
	"context"
)

const getPocketCode = `-- name: GetPocketCode :one
select user_id, code from pocket_code where user_id = $1
`

func (q *Queries) GetPocketCode(ctx context.Context, userID string) (PocketCode, error) {
	row := q.db.QueryRow(ctx, getPocketCode, userID)
	var i PocketCode
	err := row.Scan(&i.UserID, &i.Code)
	return i, err
}
