// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: getPocketToken.sql

package db

import (
	"context"
)

const getPocketToken = `-- name: GetPocketToken :one
select access_token, username, user_id from pocket_token where user_id = $1
`

func (q *Queries) GetPocketToken(ctx context.Context, userID string) (PocketToken, error) {
	row := q.db.QueryRow(ctx, getPocketToken, userID)
	var i PocketToken
	err := row.Scan(&i.AccessToken, &i.Username, &i.UserID)
	return i, err
}
