// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: getTagByIdAndUserId.sql

package db

import (
	"context"
)

const getTagByIdAndUserId = `-- name: GetTagByIdAndUserId :one
select id, name, user_id, added, updated, deleted from tag where id =$1 and user_id = $2 limit 1
`

type GetTagByIdAndUserIdParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTagByIdAndUserId(ctx context.Context, arg GetTagByIdAndUserIdParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByIdAndUserId, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}
