// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: getTagByUserAndName.sql

package db

import (
	"context"
)

const getTagByUserAndName = `-- name: GetTagByUserAndName :one
select id, name, user_id, added, updated, deleted from tag where user_id = $1 and name = $2 limit 1
`

type GetTagByUserAndNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetTagByUserAndName(ctx context.Context, arg GetTagByUserAndNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByUserAndName, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}
