// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: getUserByEmail.sql

package db

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
select id, name, email, email_verified, picture, account_password, created_at, last_login, refresh_token, deleted, signup_mode from userr where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Userr, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Userr
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Picture,
		&i.AccountPassword,
		&i.CreatedAt,
		&i.LastLogin,
		&i.RefreshToken,
		&i.Deleted,
		&i.SignupMode,
	)
	return i, err
}
