// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: getUserRootFolderByName.sql

package db

import (
	"context"
)

const getUserRootFolderByName = `-- name: GetUserRootFolderByName :one
select exists (select folder_id, user_id, folder_name, path, label, starred, created_at, updated_at, subfolder_of, deleted_at, folder_description, folder_password, ishidden from folder where user_id=$1 and deleted_at is null and subfolder_of is null and folder_name = $2)
`

type GetUserRootFolderByNameParams struct {
	UserID     string `json:"user_id"`
	FolderName string `json:"folder_name"`
}

func (q *Queries) GetUserRootFolderByName(ctx context.Context, arg GetUserRootFolderByNameParams) (bool, error) {
	row := q.db.QueryRow(ctx, getUserRootFolderByName, arg.UserID, arg.FolderName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
