// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: getUserbyEmailAndID.sql

package db

import (
	"context"
)

const getUserByEmailAndID = `-- name: GetUserByEmailAndID :one
SELECT id, name, email, email_verified, picture, account_password, created_at, last_login, refresh_token, deleted, signup_mode FROM userr
WHERE email = $1 AND id = $2
LIMIT 1
`

type GetUserByEmailAndIDParams struct {
	Email string `json:"email"`
	ID    string `json:"id"`
}

func (q *Queries) GetUserByEmailAndID(ctx context.Context, arg GetUserByEmailAndIDParams) (Userr, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAndID, arg.Email, arg.ID)
	var i Userr
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Picture,
		&i.AccountPassword,
		&i.CreatedAt,
		&i.LastLogin,
		&i.RefreshToken,
		&i.Deleted,
		&i.SignupMode,
	)
	return i, err
}
