// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Bookmark  string             `json:"bookmark"`
	Host      string             `json:"host"`
	Favicon   string             `json:"favicon"`
	Thumbnail string             `json:"thumbnail"`
	Notes     pgtype.Text        `json:"notes"`
	UserID    string             `json:"user_id"`
	Added     time.Time          `json:"added"`
	Updated   pgtype.Timestamptz `json:"updated"`
	Deleted   pgtype.Timestamptz `json:"deleted"`
}

type BookmarkTag struct {
	BookmarkID string `json:"bookmark_id"`
	TagID      string `json:"tag_id"`
}

type Tag struct {
	ID      string             `json:"id"`
	Name    string             `json:"name"`
	UserID  string             `json:"user_id"`
	Added   time.Time          `json:"added"`
	Updated pgtype.Timestamptz `json:"updated"`
	Deleted pgtype.Timestamptz `json:"deleted"`
}

type Userr struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	EmailVerified   bool               `json:"email_verified"`
	Picture         pgtype.Text        `json:"picture"`
	AccountPassword pgtype.Text        `json:"account_password"`
	CreatedAt       time.Time          `json:"created_at"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	RefreshToken    pgtype.Text        `json:"refresh_token"`
	Deleted         pgtype.Timestamptz `json:"deleted"`
}
