// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: moveFoldersToRoot.sql

package db

import (
	"context"
)

const moveFoldersToRoot = `-- name: MoveFoldersToRoot :many
update folder set path = subpath(path, nlevel((select path from folder where folder.label = $1))-1) where path <@ (
select path from folder where folder.label = $2
) returning folder_id, user_id, folder_name, path, label, starred, created_at, updated_at, subfolder_of, deleted_at, folder_description, folder_password, ishidden
`

type MoveFoldersToRootParams struct {
	Label   string `json:"label"`
	Label_2 string `json:"label_2"`
}

func (q *Queries) MoveFoldersToRoot(ctx context.Context, arg MoveFoldersToRootParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, moveFoldersToRoot, arg.Label, arg.Label_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.FolderID,
			&i.UserID,
			&i.FolderName,
			&i.Path,
			&i.Label,
			&i.Starred,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubfolderOf,
			&i.DeletedAt,
			&i.FolderDescription,
			&i.FolderPassword,
			&i.Ishidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
