// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: moveCollection.sql

package db

import (
	"context"
)

const moveCollections = `-- name: MoveCollections :many
update folder set path = (select path from folder where folder.label = $1) || subpath(path, nlevel((select path from folder where folder.label = $2))-1) where path <@ (select path from folder where folder.label = $3) returning folder_id, user_id, folder_name, path, label, starred, created_at, updated_at, subfolder_of, deleted_at, folder_description, folder_password, ishidden
`

type MoveCollectionsParams struct {
	Label   string `json:"label"`
	Label_2 string `json:"label_2"`
	Label_3 string `json:"label_3"`
}

func (q *Queries) MoveCollections(ctx context.Context, arg MoveCollectionsParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, moveCollections, arg.Label, arg.Label_2, arg.Label_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.FolderID,
			&i.UserID,
			&i.FolderName,
			&i.Path,
			&i.Label,
			&i.Starred,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubfolderOf,
			&i.DeletedAt,
			&i.FolderDescription,
			&i.FolderPassword,
			&i.Ishidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
