// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: moveBookmark.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const moveBookmark = `-- name: MoveBookmark :one
update bookmark set folder_id = $1 where id = $2 returning id, title, bookmark, host, favicon, thumbnail, notes, user_id, added, updated, deleted, folder_id, beautified, fromchrome
`

type MoveBookmarkParams struct {
	FolderID pgtype.Text `json:"folder_id"`
	ID       string      `json:"id"`
}

func (q *Queries) MoveBookmark(ctx context.Context, arg MoveBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, moveBookmark, arg.FolderID, arg.ID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Bookmark,
		&i.Host,
		&i.Favicon,
		&i.Thumbnail,
		&i.Notes,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
		&i.FolderID,
		&i.Beautified,
		&i.Fromchrome,
	)
	return i, err
}
