// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: readSupportMessages.sql

package db

import (
	"context"
)

const readSupportMessages = `-- name: ReadSupportMessages :many
select id, email, title, comment, created from support order by created desc
`

func (q *Queries) ReadSupportMessages(ctx context.Context) ([]Support, error) {
	rows, err := q.db.Query(ctx, readSupportMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Support{}
	for rows.Next() {
		var i Support
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Title,
			&i.Comment,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
