// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: renameTag.sql

package db

import (
	"context"
)

const renameTag = `-- name: RenameTag :one
update tag set name = $1 where id = $2 returning id, name, user_id, added, updated, deleted
`

type RenameTagParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) RenameTag(ctx context.Context, arg RenameTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, renameTag, arg.Name, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}
