// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: searchUserBookmarks.sql

package db

import (
	"context"
)

const searchUserBookmarks = `-- name: SearchUserBookmarks :many
SELECT id, title, bookmark, host, favicon, thumbnail, notes, user_id, added, updated, deleted, folder_id, beautified FROM bookmark
WHERE title ~~* $1 AND user_id = $2 AND deleted IS NULL
`

type SearchUserBookmarksParams struct {
	Title  string `json:"title"`
	UserID string `json:"user_id"`
}

func (q *Queries) SearchUserBookmarks(ctx context.Context, arg SearchUserBookmarksParams) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, searchUserBookmarks, arg.Title, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Bookmark,
			&i.Host,
			&i.Favicon,
			&i.Thumbnail,
			&i.Notes,
			&i.UserID,
			&i.Added,
			&i.Updated,
			&i.Deleted,
			&i.FolderID,
			&i.Beautified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
