// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: searchUserFolders.sql

package db

import (
	"context"
)

const searchUserFolders = `-- name: SearchUserFolders :many
SELECT folder_id, user_id, folder_name, path, label, starred, created_at, updated_at, subfolder_of, deleted_at, folder_description, folder_password, ishidden FROM folder
WHERE folder_name ~~* $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY (created_at) DESC
`

type SearchUserFoldersParams struct {
	FolderName string `json:"folder_name"`
	UserID     string `json:"user_id"`
}

func (q *Queries) SearchUserFolders(ctx context.Context, arg SearchUserFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, searchUserFolders, arg.FolderName, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.FolderID,
			&i.UserID,
			&i.FolderName,
			&i.Path,
			&i.Label,
			&i.Starred,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubfolderOf,
			&i.DeletedAt,
			&i.FolderDescription,
			&i.FolderPassword,
			&i.Ishidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
