// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: tagBookmark.sql

package db

import (
	"context"
)

const tagBookmark = `-- name: TagBookmark :one
INSERT INTO bookmark_tag (bookmark_id, tag_id)
VALUES ($1, $2)
RETURNING bookmark_id, tag_id
`

type TagBookmarkParams struct {
	BookmarkID string `json:"bookmark_id"`
	TagID      string `json:"tag_id"`
}

func (q *Queries) TagBookmark(ctx context.Context, arg TagBookmarkParams) (BookmarkTag, error) {
	row := q.db.QueryRow(ctx, tagBookmark, arg.BookmarkID, arg.TagID)
	var i BookmarkTag
	err := row.Scan(&i.BookmarkID, &i.TagID)
	return i, err
}
