// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: trashTag.sql

package db

import (
	"context"
)

const trashTag = `-- name: TrashTag :one
update tag set deleted = now() where id = $1 and user_id = $2 and deleted is null returning id, name, user_id, added, updated, deleted
`

type TrashTagParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) TrashTag(ctx context.Context, arg TrashTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, trashTag, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}
