// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: trashBookmark.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const trashBookmark = `-- name: TrashBookmark :one
update bookmark set deleted = $1 where id = $2 returning id, title, bookmark, host, favicon, thumbnail, notes, user_id, added, updated, deleted
`

type TrashBookmarkParams struct {
	Deleted pgtype.Timestamptz `json:"deleted"`
	ID      string             `json:"id"`
}

func (q *Queries) TrashBookmark(ctx context.Context, arg TrashBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, trashBookmark, arg.Deleted, arg.ID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Bookmark,
		&i.Host,
		&i.Favicon,
		&i.Thumbnail,
		&i.Notes,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}
