// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: updateUserLastLogin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateUserLastLoginAndRefreshToken = `-- name: UpdateUserLastLoginAndRefreshToken :one
UPDATE userr
SET last_login = $1, refresh_token = $2
WHERE id = $3
RETURNING id, name, email, email_verified, picture, account_password, created_at, last_login, refresh_token, deleted, signup_mode
`

type UpdateUserLastLoginAndRefreshTokenParams struct {
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	ID           string             `json:"id"`
}

func (q *Queries) UpdateUserLastLoginAndRefreshToken(ctx context.Context, arg UpdateUserLastLoginAndRefreshTokenParams) (Userr, error) {
	row := q.db.QueryRow(ctx, updateUserLastLoginAndRefreshToken, arg.LastLogin, arg.RefreshToken, arg.ID)
	var i Userr
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Picture,
		&i.AccountPassword,
		&i.CreatedAt,
		&i.LastLogin,
		&i.RefreshToken,
		&i.Deleted,
		&i.SignupMode,
	)
	return i, err
}
