// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: updateFolderParent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateFolderParent = `-- name: UpdateFolderParent :exec
update folder
set subfolder_of = $1
where folder_id = $2
`

type UpdateFolderParentParams struct {
	SubfolderOf pgtype.Text `json:"subfolder_of"`
	FolderID    string      `json:"folder_id"`
}

func (q *Queries) UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) error {
	_, err := q.db.Exec(ctx, updateFolderParent, arg.SubfolderOf, arg.FolderID)
	return err
}
