// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: updateBookmark.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateBookmark = `-- name: UpdateBookmark :one
update bookmark set title = $1, notes = $2 where id = $3 and user_id = $4 returning id, title, bookmark, host, favicon, thumbnail, notes, user_id, added, updated, deleted, folder_id, beautified, fromchrome
`

type UpdateBookmarkParams struct {
	Title  string      `json:"title"`
	Notes  pgtype.Text `json:"notes"`
	ID     string      `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, updateBookmark,
		arg.Title,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Bookmark,
		&i.Host,
		&i.Favicon,
		&i.Thumbnail,
		&i.Notes,
		&i.UserID,
		&i.Added,
		&i.Updated,
		&i.Deleted,
		&i.FolderID,
		&i.Beautified,
		&i.Fromchrome,
	)
	return i, err
}
